name: pwms

services:
  pwms.api:
    image: jtojoj/pwms.api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_ENABLE_GRPC_INSTRUMENTATION: 1
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
