name: pwms

services:
  pwmsdb:
    image: postgres:latest
    container_name: pwmsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin1234!
      - POSTGRES_DB=PWMS
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_pwms:/var/lib/postgresql/data/

  keycloakdb:
    image: postgres:15.6
    container_name: keycloakdb
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 5001:8080

volumes:
  postgres_pwms:
  postgres_keycloak:
