global using DotNet.Testcontainers.Builders;
global using DotNet.Testcontainers.Containers;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Moq;
global using PWMS.Application.Common.Interfaces;
global using PWMS.Infrastructure.Core.Services;
global using System.Diagnostics.CodeAnalysis;